version: "3"

services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongodb:/data/mongodb
        networks:
            - goals-net

    backend:
        container_name: backend-node
        image: backend-node:latest
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        networks:
            - goals-net
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - mongodb

    frontend:
        container_name: frontend-react
        image: frontend-react:latest
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        networks:
            - goals-net
        volumes:
            - ./frontend:/app
            - /app/node_modules
        depends_on:
            - backend
        stdin_open: true

networks:
    goals-net:
