version: "3"

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data/redis
        networks:
            - goals-net

    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongodb:/data/mongodb
        networks:
            - goals-net

    backend:
        image: backend-node:latest
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend-node
        ports:
            - "4000:4000"
        networks:
            - goals-net
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - redis
            - mongodb

    frontend:
        image: frontend-react:latest
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend-react
        ports:
            - "3000:80"
        networks:
            - goals-net
        volumes:
            - ./frontend:/app
            - /app/node_modules
        depends_on:
            - backend
        environment:
            CHOKIDAR_USEPOLLING: true
        stdin_open: true

networks:
    goals-net:
