version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/data/redis:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/data/mongodb:/data/db

  backend:
    image: backend-node:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-node
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis
      - mongodb

  frontend:
    image: frontend-react:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: true
