@port = 4000
@protocol = http
@hostname = localhost
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNkNGVmMWRjMTMzNzkwMGQzMjI1MTdiIiwiaWF0IjoxNjc0ODk5MjI5LCJleHAiOjE2NzQ5MzUyMjl9.h1ROAQMrs3cH2gl5IaXrek56SF4eNwRx4Wu3GOdgNYQ

@host = {{hostname}}:{{port}}
@baseUrl = {{protocol}}://{{host}}


### Signin
POST {{baseUrl}}/api/auth/signin
Content-Type: {{contentType}}

{
    "password": "1234",
    "email": "tacuong@gmail.com"
}


### Signup
POST {{baseUrl}}/api/auth/signup
Content-Type: {{contentType}}

{
    "name": "Ta Cuong",
    "password": "1234",
    "email": "tacuong@gmail.com"
}

### Signout
GET {{baseUrl}}/api/auth/signout
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### Update password
PUT  {{baseUrl}}/api/auth/update_password
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "new_password": "12345",
    "current_password": "1234"
}
