@port = 4000
@protocol = http
@hostname = localhost
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNkNjA5NTQ4MmEyZTcwMDFkMWI1YTU4IiwiaWF0IjoxNjc0OTcyNTk1LCJleHAiOjE2NzQ5NzI1OTV9.d9qhw4Gwv_GYnV_FRxPBDEwd7z_f6cwL3V7m5Kd8D3o

@host = {{hostname}}:{{port}}
@baseUrl = {{protocol}}://{{host}}


### Get notifications
GET {{baseUrl}}/api/notification
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### Read notification
PUT {{baseUrl}}/api/notification/read/63d5da8345e7b7001ef182a9
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### Read all notification
PUT {{baseUrl}}/api/notification/read-all
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### Get notification by key
PUT {{baseUrl}}/api/notification/get-by-key/friend-create-post
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}