@port = 4000
@protocol = http
@hostname = localhost
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNkNjA5NTQ4MmEyZTcwMDFkMWI1YTU4IiwiaWF0IjoxNjc0OTc0NjU0LCJleHAiOjE2NzQ5NzQ2NTR9.oAOvPmPlVlbaim162TA3uXt1X7BpaL-qsWUHtuvgics

@host = {{hostname}}:{{port}}
@baseUrl = {{protocol}}://{{host}}


### Create post
POST {{baseUrl}}/api/post/
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "privacy": "public",
    "body": {
        "tag_friends": [],
        "feelings": "Happy",
        "location": "Ha Noi"
    },
    "text": "Happy new year 2023",
    "images": "https://firebasestorage.googleapis.com/v0/b/social-media-app-8ecd4.appspot.com/o/images%2Fprofile_pic%2FTa%20Cuong-1674959572267-astronaut-space_378362-1429.avif?alt=media&token=6ffd5ac9-45f8-4220-9b2d-36efd8e28047"
}


### React post
POST {{baseUrl}}/api/post/react-post/63d5da8345e7b7001ef182a9?key=love
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### Delete post
DELETE {{baseUrl}}/api/post/63d5da8345e7b7001ef182a9
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### Edit post
DELETE {{baseUrl}}/api/post/63d5da8345e7b7001ef182a9
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "privacy": "public",
    "content": "Hahaa",
    "images": ["https://firebasestorage.googleapis.com/v0/b/social-media-app-8ecd4.appspot.com/o/images%2Fprofile_pic%2FTa%20Cuong-1674959572267-astronaut-space_378362-1429.avif?alt=media&token=6ffd5ac9-45f8-4220-9b2d-36efd8e28047"]
}

### Get posts
GET {{baseUrl}}/api/post/
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}
