@port = 4000
@protocol = http
@hostname = localhost
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjNkNjA5NTQ4MmEyZTcwMDFkMWI1YTU4IiwiaWF0IjoxNjc0OTcxNDc2LCJleHAiOjE2NzQ5NzE0NzZ9.5PbrIrfrzCW7HVfremfVNz-US2jSV2jZFiu-Zw4d0lE

@host = {{hostname}}:{{port}}
@baseUrl = {{protocol}}://{{host}}


### Current user
GET {{baseUrl}}/api/user/me
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### Searh
GET {{baseUrl}}/api/user/search?name=Super Idol
Content-Type: {{contentType}}


### Get by ID
GET {{baseUrl}}/api/user/63d5da8345e7b7001ef182a9
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### Update cover image
PUT {{baseUrl}}/api/user/cover-image
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "cover_image": "https://firebasestorage.googleapis.com/v0/b/social-media-app-8ecd4.appspot.com/o/images%2Fprofile_pic%2FTa%20Cuong-1674959572267-astronaut-space_378362-1429.avif?alt=media&token=6ffd5ac9-45f8-4220-9b2d-36efd8e28047"
}


### Update avatar image
PUT {{baseUrl}}/api/user/avatar-image
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "avatar_image": "https://firebasestorage.googleapis.com/v0/b/social-media-app-8ecd4.appspot.com/o/images%2Fprofile_pic%2FTa%20Cuong-3d-rendering-hoodie-melting_23-2150083285.avif?alt=media&token=ade08ed8-af7d-4e1d-aab7-5b1da88bfb79"
}


### Update profile
PUT {{baseUrl}}/api/user/update-profile
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "name": "Cuong VT",
    "education": "HaUI",
    "hometown": "Ha Noi",
    "email": "cuongvt@gmail.com",
}


### Get recommend user
GET {{baseUrl}}/api/user/recommend-users
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}
